### ISSUE TITLE
502 bad gateway with no email permission

### ISSUE THREAD

**Issue by agentd00nut** [mAzurkovic/BandoMap#5]
I tried to login through facebook as a first time user.

I didn't want to share my email with bandomap so clicked that permission off.

I got redirected to `https://bandomap.com/auth/facebook/callback?` ( with my code of course ) and i get a 502 bad gateway.

Interestingly if i pass an invalid code it throws an error about invalid code format.

**Comment by mAzurkovic** [comment]
Ok I am looking into it. It could be because when the app is saving a new user, the `email` parameter needs a String, and when no email is specified it could be passing a random object or something like that. Hopefully it will be solved with a simple conditional. 👍

**Comment by mAzurkovic** [comment]
Fixed!
